### ISSUE TITLE
Allow automatic TLBID/IID/CLSID specifier

### ISSUE THREAD

**Issue by Rantanen** [Rantanen/intercom#1]
The various `#[com_...]` attributes require GUIDs as parameters. These are used to define the various `IID_...`, `CLSID_...`, etc. global GUIDs.

Currently the user needs to specify them here but they aren't seemingly used anywhere else.

It would be more convenient if the user was able to specify the GUIDs with something like;

```rust
#[com_class( AUTO_GUID, IComInterface )]
pub struct Foo { ... }
```

When the `com_class` is expanded (intercom-attributes/src/lib.rs, `expand_com_class`), instead of reading the GUID from the attribute as is, the GUID is generated in a deterministic way based on the current crate and the item name.

ie. something along the lines of:

```rust
AUTO_GUID => Guid::random_seed( env!("CARGO_PKG_NAME") + current_item_name )
```

----------------------------------

Tasks:

- Implement deterministic GUID generation. This should be in the `intercom::Guid`.
- Accept AUTO_GUID when parsing the GUID attribute parameter.
- Ensure the attributes (intercom-attributes) and the IDL generation (intercom-utils) result in the same GUIDs.

All of this should happen at runtime during attribute expansion or IDL generation. There should be no major changes in the generated code.

**Comment by Fluxie** [comment]
RFC-4122 describes how to generate name based UUIDs. See https://tools.ietf.org/html/rfc4122#section-4.3

The version field in the RFC defined UUID ensures we don't accidentally tramble on UUIDs generated with some different method.
