### ISSUE TITLE
Stronger concept of com interface

### ISSUE THREAD

**Issue by Rantanen** [Rantanen/intercom#16]
Currently things like the IID is available only as a convention of having the `IID_` prefix.

We could turn this into a trait instead where the IID of an interface was available through something similar to `IInterface::iid_of()` or `( IInterface as IIDOf )::iid_of()` if the former doesn't work.

This would allow us to do all kinds of fancy things, such as providing a strongly typed version of `query_interface`. Something similar to:

```rust
let new_interface = old_interface.query_interface::<INew>()

// Given
fn query_interface<T : IIDOf>( &self ) -> T {
    self.query_interface( T::iid_of() )
}
```

**Comment by Boddlnagg** [comment]
I'm doing something like this in winrt-rust: https://github.com/contextfree/winrt-rust/blob/9d1b87b86c3c5efcbc132ec4ef161197a9576ffd/src/comptr.rs#L92-L94

The winapi 0.3 crate is also adding a `uuidof` function to every interface, see https://github.com/retep998/winapi-rs/blob/92b6629342f84a5c49ef09d58e60b819f4b12efb/src/lib.rs#L57-L59 and https://github.com/retep998/winapi-rs/blob/92b6629342f84a5c49ef09d58e60b819f4b12efb/src/macros.rs#L232-L247 .

By the way, there's also https://github.com/retep998/wio-rs/blob/master/src/com.rs (but not actively developed).

**Comment by Rantanen** [comment]
Yeah, this is similar to what I am aiming for as well.

I knew of winapi's `uuidof`. We've also discussed the compatibility between this library and `winapi` with retep998. I would love these two crates to work together rather seamlessly - however I don't want to depend on `winapi` because of my goal to support Linux and other systems on the binary level.
