### ISSUE TITLE
Interface types are not gathered in typelib

### ISSUE THREAD

**Issue by dontpanic92** [Rantanen/intercom#174]
In `__gather_module_types`, interface types are not gathered. As a result, interfaces cannot be exported in IDL when I write

```
com_library! {
    interface IFoo
}
```

https://github.com/Rantanen/intercom/blob/f6728c2c6add9f9c42b084359d637e2b4fda407e/intercom-common/src/attributes/com_library.rs#L172-L181

Is that by design? I can get it work by simply adding a `create_interface_typeinfo` there

**Comment by Rantanen** [comment]
It's unimplemented.

Back when `__gather_module_types` was implemented, the `com_library` didn't support anything but classes and instead the interfaces were gathered from the `create_class_typeinfo` by figuring out what interfaces the classes implement. I'll add that and ensure there's no issues if an interface is both exported by `com_library` and also referenced by a class (and exported that way).
