### ISSUE TITLE
Hide Windows API behind a feature

### ISSUE THREAD

**Issue by Rantanen** [Rantanen/intercom#18]
Currently we have `#[cfg(windows)]` and `#[cfg(not(windows))]` in few places. This makes it impossible to exercise the non-Windows code when compiling on Windows.

It would be better if these were configured using features instead - this would allow building Intercom on Windows without the dependencies on Windows API and thus achieving the same compilation results as Linux got. Making it less likely to break Linux builds by accident.

**Comment by Fluxie** [comment]
Should we just call the feature "com"?

If we call it "windows" then the feature flag feels sort of mandatory when compiling for Windows. I don't see a reason why we could not deliver pure C++ interoperability in Windows too.

**Comment by Rantanen** [comment]
I'd go with `winapi` or similar.

I still don't agree with the notion that `com` is somehow inherently Windows. There's already prior art in non-Windows COM:

- Apple's Core Foundation (OSX/iOS low level platform API) has [plugins](https://developer.apple.com/library/content/documentation/DeviceDrivers/Conceptual/AccessingHardware/AH_Device_Access_IOKit/AH_Device_Access_IOKit.html#//apple_ref/doc/uid/TP30000378-CJAHAHFC) based on COM. 
- Mozilla's [Cross platform COM](https://en.wikipedia.org/wiki/XPCOM)

Note this issue is meant to disable the use of things like `SysAllocStringLen`, etc. Not alter the whole COM binary API.

**Comment by Fluxie** [comment]
I think "winapi" is good.

**Comment by Rantanen** [comment]
Closing in favor of #32
