### ISSUE TITLE
Build fails with syn 1.0.60

### ISSUE THREAD

**Issue by saschanaz** [Rantanen/intercom#187]
`Item::__Nonexhaustive` does not exist anymore and replaced by `::TestExhaustive`.

**Comment by Rantanen** [comment]
Really shouldn't have used `__Nonexhaustive` to begin with. Must not have been thinking straight when I've implemented that!

Fixed now to use `_` as opposed to relying on some specific exhaustiveness.

**Comment by saschanaz** [comment]
Confirmed, closing 👍
