### ISSUE TITLE
Custom hooks for DllRegisterServer/DllUnregisterServer?

### ISSUE THREAD

**Issue by saschanaz** [Rantanen/intercom#188]
It could be great for registry modification, merging association.reg in the thumbnail example into the code for example.

**Comment by Rantanen** [comment]
Had a stab at it over at #190 on an API level. Didn't have time to put it into use yet in the thumbnail provider example.

**Comment by Rantanen** [comment]
Absolutely no idea why I didn't merge this in back in the day (I guess I was waiting for myself to find time to implement the usage in the thumbnail example?). Merged now.
