### ISSUE TITLE
Consensus on what cross platform support for Intercom means

### ISSUE THREAD

**Issue by Rantanen** [Rantanen/intercom#23]
- [x] Must the binary interface change?
    - Call convention must change between `stdcall` and `C` because of compiler differences and `stdcall` being required on Windows.
- [x] Should the binary interface change?
   - Other than the call convention, no other interface changes.
- [ ] What to do with error values?
   - Opened a separate issue #33
- [x] Can/should we still call it COM?
   - It's still following Component Object Model binary interface standard. I'm fine downplaying its importance, but I don't think it's technically wrong. Even Microsoft is referring to their COM implementation as "Microsoft COM".
- [x] Can/should we still call this Intercom?
   - For now, yes. But specifically "[Intercom](https://en.wikipedia.org/wiki/Intercom)", not "InterCom" - this is to downplay the COM part.

### My vision

If the binary interface doesn't need to change because of compiler differences, then it shouldn't change. At least there shouldn't be any functional changes in how the parameters and return values are handled. The traits-to-vtables translation logic is the most complex part of Intercom. It would be better if we didn't add more complexity into it by adding more ways to handle how `Result<T,E>`s and such are converted from traits to extern-compatible method signatures.

For similar reasons we would keep the basic error values the same. Current `S_OK`, `E_NOINTERFACE`, `E_POINTER`, `E_INVALIDARG` and `E_FAIL` would stay. Possibly `E_NOTIMPL` as well. These are error values that we need for the base interfaces, such as `DllGetClassObject`, `CreateInstance` and `QueryInterface`. Also [numeric error codes as return values](http://www-numi.fnal.gov/offline_software/srt_public_context/WebDocs/Errors/unix_system_errors.html) is a concept that is common for various platforms.

Currently we define some other error codes in addition to these. These include codes like `E_ACCESSDENIED` but also `STG_E_FILENOTFOUND`, etc. These we might want to make platform specific - maybe even remove the current definitions and rely on the raw OS errors as [exposed by Rust](https://doc.rust-lang.org/std/io/struct.Error.html#method.raw_os_error). These are needed for converting errors anyway - not something that we rely on internally.

Finally, when it comes to naming, I would still keep referring to the communication protocol as COM. As I mentioned in #18, there is prior art for COM on other platforms in:

- Apple's [Core Foundation](https://developer.apple.com/library/content/documentation/DeviceDrivers/Conceptual/AccessingHardware/AH_Device_Access_IOKit/AH_Device_Access_IOKit.html#//apple_ref/doc/uid/TP30000378-CJAHAHFC)
- Mozilla's [XPCOM](https://en.wikipedia.org/wiki/XPCOM)

However this would be strictly limited to "COM protocol" or "COM interface" instead of COM platform/API/SDK/framework, which might imply runtime services which we do not provide. Also any terminology related to OLE, OLE Automation, Automation, ActievX, etc. should be avoided unless specifically describing compatibility solutions targeting these technologies.

If we accept COM to describe the C++-virtual-table-compatible-binary-protocol, then I don't see why we couldn't keep using Intercom as the crate name. It's ambiguous enough that even without COM I could make a case for it!

- **Inter**-(platform/language/operation) **COM**
- **Inter**-(platform/language) **Com**munication
- **Inte**ntionally ambiguous **R**ust-**C**++ **O**bject **M**odel \\:D/

**Comment by Rantanen** [comment]
Poking @Fluxie for comments

This also relates to #22. If we keep the binary interface the same, then I would love to have the current C++ unit tests exercised over GCC/LLVM as well. We would hide the current Windows `CoInitialize`/`CreateInstance` etc. calls hidden behind platform specific methods, but the actual interface invocations should be implementable over GCC/LLVM as well.

Furthermore this relates to how we expose C++ interop for Intercom. Part of me believes we should do this in layers.

- The first layer is what we have now on Windows without ATL, etc.
  - Raw interface pointers, need to call `AddRef` and such manually, etc.
  - This would provide a very low level access to the Intercom libraries. Allowing us to use C++ to write low level tests for Intercom. I believe it is important to have one language/platform that we can use to write low level tests to ensure the basic implementation works for all platforms. Doing this in Rust is [pain](https://github.com/Rantanen/intercom/blob/0d0eadba70313b4f9ef434477f5fe9c39e83130a/com_library/examples/example.rs#L71-L76) so C++ would be the logical choice.
- The second layer is the one we want our users to use. This would probably be something template-based or similar and focuses on ease of use.
  - Unit tests written for this layer are similar to our current C# tests: Their intention is to ensure the Intercom APIs map well to this layer. Just like C# tests ensure errors are mapped properly to exceptions, etc.

To highlight the difference in testing. Our current C++ tests include things such as [ensuring the ref counts are correct](https://github.com/Rantanen/intercom/blob/master/test/cpp/iunknown.cpp#L62-L110). These tests exercise functionality that affects all COM clients: C++, C#, etc. and because of this we want these tests to be executed on all the supported platforms.

Our C# tests on the other hand are more focused on ensuring that the COM interfaces, as implemented by Intercom, behave well from C# point of view. Things like [HRESULTs getting mapped to exceptions](https://github.com/Rantanen/intercom/blob/master/test/cs/ErrorInfoSupport.cs) are tested here. These tests are only applicable to the C#/.Net implementations.

**Comment by Boddlnagg** [comment]
When you're talking about COM on other platforms, one could also mention OpenOffice's (and LibreOffice's) UNO, which is at least inspired by COM (I don't know in what way it could be called "compatible") ... see https://wiki.openoffice.org/wiki/Documentation/DevGuide/ProUNO/Using_UNO_Interfaces.

**Comment by Rantanen** [comment]
Had no idea that existed, thanks for pointing it out!

Doesn't seem to be COM-compatible, which is probably the reason they don't refer to it with COM terminology. It's definitely inspired by COM, but there's few crucial differences, such as using exceptions for error handling, which needs deeper run-time support as exceptions aren't binary compatible between languages and need to be translated to some sort of error codes and then re-thrown.

When I started this project, all I knew was XPCOM. The fact that there are more COM or COM-inspired implementations on other platforms gives a bit more faith in the sanity of pursuing the cross platform story with the library. :)

**Comment by Rantanen** [comment]
Also clarifying that the current vision is just that, a vision. There's only few things that I feel rather strongly about:

- Changing from "Microsoft COM" to "Cross platform COM" should be as simple as changing a feature flag or similar. There should be no need to rewrite the Rust code. This allows people to write Rust components that work "natively" on Windows and are still usable cross platform on other platforms.
  - However the other direction isn't as important. A Cross platform compatible trait doesn't need to be "Microsoft COM" compatible. Essentially I see the possible "Cross platform COM" as COM free of Microsoft limitations, such as the need/recommendation to use BSTRs, etc.
- We should do our best to enable sharing at least one test suite between different platforms. While this could be a Rust-suite, it would be better if it was a C++-suite as that would better mimic the expected real world usage scenarios.
- We should avoid adding complicated platform-specific changes in the interface generation `[com_...]` attributes.
  - Things like "disabling BStr conversion" are okay in my eyes as long as they are behind configuration features and supported by the selected unit test bindings (such as C++) on all operating systems.
  - Things like "all-numbers-as-128-bit" are not okay (without good reasoning):
    - Currently our numeric types do not need conversion. Adding conversion for them complicates the code in multiple places.
    - `__int128` is not supported on MSVC
  - On the other hand "supporting 128-bit numbers" might be okay if it's seen as high value.
    - Adding a new type support is business as usual.
    - `i128`/`u128` might not be FFI safe, so this might need type conversion - but we already have that infra for things like `String` <-> `BStr` so it wouldn't be built specifically for this.

While the last point is not a strict rule and just needs to be considered on case by case basis, an important consideration for it is not only the complexity of the implementation but also the accrued complexity in maintaining the implementation when making future changes. This is also why it is important that the features would be testable on all platforms.

Currently we have issues in the testability with things like `IErrorInfo` and `BStr` - but we do have a somewhat sane long term plan for `BStr` in the form of #6 and I'm sure we can come up with something for `IErrorInfo` once we can figure out how we want cross platform errors to be handled. #6 on its own doesn't make much sense, but it is still worth it just to get our `BStr` tests running on non-Windows platforms.

**Comment by Rantanen** [comment]
The cross-platform story has evolved and we (I?) now have a good understanding of what this means.

I should write this up as a document in the repository and link it from the README.md at some point, but currently the vision is in #32.
